cmake_minimum_required(VERSION 3.28)

if(NOT DEFINED SITOMETRON_SOURCE_DIR)
  get_filename_component(SITOMETRON_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(V1 "${SITOMETRON_SOURCE_DIR}/schemas/core/v1")
set(COMMAND_SCHEMA_PATH "${V1}/job-command.schema.json")
set(CANDIDATE_SCHEMA_PATH "${V1}/job-candidate-event.schema.json")
set(REDUCER_INPUT_SCHEMA_PATH "${V1}/job-reducer-input-event.schema.json")
set(JOURNAL_SCHEMA_PATH "${V1}/job-journal-event.schema.json")
set(REJECTION_SCHEMA_PATH "${V1}/job-rejection.schema.json")
set(SNAPSHOT_SCHEMA_PATH "${V1}/job-reducer-snapshot.schema.json")
set(CONTRACT_SCHEMA_PATH "${V1}/job-reducer-contract.schema.json")
set(CONTRACT_PATH "${V1}/job-reducer-contract.json")
set(VECTORS_SCHEMA_PATH "${V1}/job-reducer-vectors.schema.json")
set(VECTORS_PATH "${V1}/job-reducer-vectors.json")
set(DIAGRAM_PATH "${V1}/job-state-diagram.dot")

foreach(path IN ITEMS
        "${COMMAND_SCHEMA_PATH}"
        "${CANDIDATE_SCHEMA_PATH}"
        "${REDUCER_INPUT_SCHEMA_PATH}"
        "${JOURNAL_SCHEMA_PATH}"
        "${REJECTION_SCHEMA_PATH}"
        "${SNAPSHOT_SCHEMA_PATH}"
        "${CONTRACT_SCHEMA_PATH}"
        "${CONTRACT_PATH}"
        "${VECTORS_SCHEMA_PATH}"
        "${VECTORS_PATH}"
        "${DIAGRAM_PATH}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Required core contract artifact is missing: ${path}")
  endif()
endforeach()

file(READ "${COMMAND_SCHEMA_PATH}" command_schema)
file(READ "${CANDIDATE_SCHEMA_PATH}" candidate_schema)
file(READ "${REDUCER_INPUT_SCHEMA_PATH}" reducer_input_schema)
file(READ "${JOURNAL_SCHEMA_PATH}" journal_schema)
file(READ "${REJECTION_SCHEMA_PATH}" rejection_schema)
file(READ "${SNAPSHOT_SCHEMA_PATH}" snapshot_schema)
file(READ "${CONTRACT_SCHEMA_PATH}" contract_schema)
file(READ "${CONTRACT_PATH}" contract)
file(READ "${VECTORS_SCHEMA_PATH}" vectors_schema)
file(READ "${VECTORS_PATH}" vectors)
file(READ "${DIAGRAM_PATH}" diagram)

function(read_string_array json output)
  set(path ${ARGN})
  string(JSON length LENGTH "${json}" ${path})
  set(values "")
  if(length GREATER 0)
    math(EXPR last "${length} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON value GET "${json}" ${path} ${index})
      list(APPEND values "${value}")
    endforeach()
  endif()
  set(${output} "${values}" PARENT_SCOPE)
endfunction()

function(read_event_definition_refs schema output)
  string(JSON count LENGTH "${schema}" oneOf)
  math(EXPR last "${count} - 1")
  set(values "")
  foreach(index RANGE 0 ${last})
    string(JSON reference GET "${schema}" oneOf ${index} "$ref")
    if(NOT reference MATCHES "^job-journal-event.schema.json#/[$]defs/[A-Za-z][A-Za-z0-9]*$")
      message(FATAL_ERROR "Event schema has an unexpected reference: ${reference}")
    endif()
    string(REGEX REPLACE "^.*/" "" definition "${reference}")
    list(APPEND values "${definition}")
  endforeach()
  set(${output} "${values}" PARENT_SCOPE)
endfunction()

function(assert_unique values label)
  set(original ${values})
  set(unique ${values})
  list(REMOVE_DUPLICATES unique)
  list(LENGTH original original_length)
  list(LENGTH unique unique_length)
  if(NOT original_length EQUAL unique_length)
    message(FATAL_ERROR "${label} contains duplicate values")
  endif()
endfunction()

function(json_signature json output)
  set(path ${ARGN})
  string(JSON type ERROR_VARIABLE error TYPE "${json}" ${path})
  if(NOT error STREQUAL "NOTFOUND")
    set(${output} "MISSING" PARENT_SCOPE)
    return()
  endif()
  if(type STREQUAL "NULL")
    set(signature "NULL")
  else()
    string(JSON value GET "${json}" ${path})
    set(signature "${type}:${value}")
  endif()
  set(${output} "${signature}" PARENT_SCOPE)
endfunction()

# Validate draft declarations and document identities without adding a package-manager dependency.
foreach(schema_name IN ITEMS command candidate reducer_input journal rejection snapshot contract vectors)
  string(JSON draft GET "${${schema_name}_schema}" "$schema")
  if(NOT draft STREQUAL "https://json-schema.org/draft/2020-12/schema")
    message(FATAL_ERROR "${schema_name} schema must use JSON Schema draft 2020-12")
  endif()
endforeach()

string(JSON contract_version GET "${contract}" contract_version)
string(JSON contract_status GET "${contract}" status)
string(JSON authority GET "${contract}" authority)
string(JSON case_semantics GET "${contract}" case_semantics)
string(JSON contract_schema_id GET "${contract_schema}" "$id")
string(JSON declared_contract_schema GET "${contract}" "$schema")
if(NOT contract_status MATCHES "^(proposed|normative|deprecated|superseded)$")
  message(FATAL_ERROR "Unknown core contract status: ${contract_status}")
endif()
if(NOT contract_version EQUAL 1 OR NOT authority STREQUAL "ADR-0002" OR
   NOT case_semantics STREQUAL "ordered_first_match" OR
   NOT declared_contract_schema STREQUAL contract_schema_id)
  message(FATAL_ERROR "Unexpected core contract identity, schema, or case semantics")
endif()

string(JSON vectors_version GET "${vectors}" contract_version)
string(JSON vectors_status GET "${vectors}" status)
string(JSON vectors_authority GET "${vectors}" authority)
string(JSON vectors_schema_id GET "${vectors_schema}" "$id")
string(JSON declared_vectors_schema GET "${vectors}" "$schema")
if(NOT vectors_version EQUAL contract_version OR NOT vectors_status STREQUAL contract_status OR
   NOT vectors_authority STREQUAL authority OR NOT declared_vectors_schema STREQUAL vectors_schema_id)
  message(FATAL_ERROR "Vector identity, status, or schema differs from the core contract")
endif()
string(JSON declared_candidate_schema GET "${contract}" candidate_event_schema)
string(JSON candidate_schema_id GET "${candidate_schema}" "$id")
string(JSON declared_reducer_input_schema GET "${contract}" reducer_input_event_schema)
string(JSON reducer_input_schema_id GET "${reducer_input_schema}" "$id")
if(NOT declared_candidate_schema STREQUAL candidate_schema_id OR
   NOT declared_reducer_input_schema STREQUAL reducer_input_schema_id)
  message(FATAL_ERROR "Candidate or internal reducer-input schema identity differs from the contract")
endif()
string(JSON session_identity_source GET "${snapshot_schema}" properties session_id
       x-sitometron-equals-field)
if(NOT session_identity_source STREQUAL "job_id")
  message(FATAL_ERROR "The snapshot schema must declare the v0.1 Job/Session identity equality")
endif()
string(JSON timer_generation_scope GET "${contract}" timer_ingress_contract generation_scope)
if(NOT timer_generation_scope STREQUAL "per_timeout_phase")
  message(FATAL_ERROR "Timer generation must be independently scoped per timeout phase")
endif()
read_string_array("${contract}" ack_bind_events terminal_worker_ack_contract bind_on_events)
read_string_array("${contract}" ack_identity_fields terminal_worker_ack_contract identity_fields)
string(JSON ack_emit_after GET "${contract}" terminal_worker_ack_contract emit_after)
string(JSON ack_delivery_owner GET "${contract}" terminal_worker_ack_contract delivery_owner)
string(JSON ack_delivery_semantics GET "${contract}" terminal_worker_ack_contract delivery_semantics)
string(JSON ack_clear_on GET "${contract}" terminal_worker_ack_contract clear_on)
string(JSON terminal_commit_clears GET "${contract}" terminal_worker_ack_contract
       terminal_commit_clears_binding)
set(expected_ack_bind_events worker_completed worker_failed)
set(expected_ack_identity_fields worker_id event_sequence)
if(NOT ack_bind_events STREQUAL expected_ack_bind_events OR
   NOT ack_identity_fields STREQUAL expected_ack_identity_fields OR
   NOT ack_emit_after STREQUAL "synced_terminal_outcome_committed" OR
   NOT ack_delivery_owner STREQUAL "phase_2_worker_adapter" OR
   NOT ack_delivery_semantics STREQUAL "idempotent_retry_until_ack_or_process_exit" OR
   NOT ack_clear_on STREQUAL "first_accepted_process_exit_confirmed" OR terminal_commit_clears)
  message(FATAL_ERROR "Terminal Worker-event ACK contract differs from ADR-0002")
endif()

read_string_array("${contract}" states job_states)
read_string_array("${contract}" terminal_states terminal_states)
read_string_array("${contract}" positions entity_positions)
read_string_array("${contract}" commands command_kinds)
read_string_array("${contract}" events journal_event_kinds)
read_string_array("${contract}" raw_candidate_events raw_candidate_event_kinds)
read_string_array("${contract}" command_produced_events command_produced_event_kinds)
read_string_array("${contract}" reducer_normalized_events reducer_normalized_event_kinds)
read_string_array("${contract}" timeout_phases timeout_phases)
read_string_array("${contract}" terminal_outcomes terminal_outcomes)
read_string_array("${contract}" dispositions dispositions)
read_string_array("${contract}" rejections rejection_reasons)
read_string_array("${contract}" effects post_sync_effects)
read_string_array("${snapshot_schema}" snapshot_fields required)

set(expected_states admitted preparing running stopping finalizing succeeded failed cancelled terminated timed_out)
set(expected_terminal_states succeeded failed cancelled terminated timed_out)
set(expected_commands cancel terminate)
set(expected_reducer_input_definitions
    jobCreated
    resourcesCommitted
    workerLaunchIntent
    workerLaunchObserved
    workerRunning
    cancelAccepted
    terminateAccepted
    timeoutExpired
    workerCompleted
    workerFailed
    processExitConfirmed
    sessionRetainRequested
    sessionRetained
    finalizationCompleted
    finalizationFailed
    terminalOutcomeCommitted
    resourcesReleased
    cleanupStatusRecorded
    lateWorkerEvent)
set(expected_candidate_definitions ${expected_reducer_input_definitions})
list(REMOVE_ITEM expected_candidate_definitions cancelAccepted terminateAccepted lateWorkerEvent)
read_event_definition_refs("${candidate_schema}" candidate_definitions)
read_event_definition_refs("${reducer_input_schema}" reducer_input_definitions)
set(expected_command_produced_events cancel_accepted terminate_accepted)
set(expected_reducer_normalized_events late_worker_event)
set(expected_raw_candidate_events ${events})
list(REMOVE_ITEM expected_raw_candidate_events ${expected_command_produced_events}
                 ${expected_reducer_normalized_events})
set(expected_dispositions transition audit late_audit reject)
set(expected_positions absent ${expected_states})
if(NOT states STREQUAL expected_states OR NOT terminal_states STREQUAL expected_terminal_states OR
   NOT commands STREQUAL expected_commands OR NOT dispositions STREQUAL expected_dispositions OR
   NOT positions STREQUAL expected_positions OR
   NOT raw_candidate_events STREQUAL expected_raw_candidate_events OR
   NOT command_produced_events STREQUAL expected_command_produced_events OR
   NOT reducer_normalized_events STREQUAL expected_reducer_normalized_events OR
   NOT candidate_definitions STREQUAL expected_candidate_definitions OR
   NOT reducer_input_definitions STREQUAL expected_reducer_input_definitions)
  message(FATAL_ERROR "Closed core enum differs from ADR-0002")
endif()
foreach(list_name IN ITEMS states terminal_states positions commands events timeout_phases
                           terminal_outcomes dispositions rejections effects snapshot_fields)
  assert_unique("${${list_name}}" "${list_name}")
endforeach()

# Strict DTO schemas and the reducer contract expose the same closed identifiers.
read_string_array("${command_schema}" schema_commands properties command_type enum)
read_string_array("${rejection_schema}" schema_rejections properties reason enum)
read_string_array("${journal_schema}" schema_timeout_phases "$defs" timeoutExpired properties payload
                  properties phase enum)
read_string_array("${journal_schema}" schema_terminal_outcomes "$defs" terminalOutcomeCommitted properties
                  payload properties outcome enum)
if(NOT schema_commands STREQUAL commands OR NOT schema_rejections STREQUAL rejections OR
   NOT schema_timeout_phases STREQUAL timeout_phases OR
   NOT schema_terminal_outcomes STREQUAL terminal_outcomes)
  message(FATAL_ERROR "A DTO JSON Schema differs from the reducer contract")
endif()

set(schema_events "")
string(JSON journal_variant_count LENGTH "${journal_schema}" oneOf)
math(EXPR journal_variant_last "${journal_variant_count} - 1")
foreach(index RANGE 0 ${journal_variant_last})
  string(JSON ref GET "${journal_schema}" oneOf ${index} "$ref")
  string(REPLACE "#/$defs/" "" def_name "${ref}")
  string(JSON schema_event GET "${journal_schema}" "$defs" "${def_name}" properties event_type const)
  list(APPEND schema_events "${schema_event}")
  set("EVENT_DEF_${schema_event}" "${def_name}")
endforeach()
if(NOT schema_events STREQUAL events)
  message(FATAL_ERROR "JobJournal event JSON Schema differs from the reducer contract")
endif()

function(is_uuid_v7 value output)
  if(value MATCHES "^[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-7[0-9a-f][0-9a-f][0-9a-f]-[89ab][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]$")
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(is_uuid_v4 value output)
  if(value MATCHES "^[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f]-4[0-9a-f][0-9a-f][0-9a-f]-[89ab][0-9a-f][0-9a-f][0-9a-f]-[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]$")
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(is_sha256 value output)
  string(LENGTH "${value}" length)
  if(length EQUAL 64 AND value MATCHES "^[0-9a-f]+$")
    set(${output} TRUE PARENT_SCOPE)
  else()
    set(${output} FALSE PARENT_SCOPE)
  endif()
endfunction()

function(is_uint64_nonzero value output)
  string(LENGTH "${value}" length)
  if(value MATCHES "^[1-9][0-9]*$" AND length LESS 21)
    set(valid TRUE)
  elseif(value MATCHES "^[1-9][0-9]*$" AND length EQUAL 20 AND
         NOT value STRGREATER "18446744073709551615")
    set(valid TRUE)
  else()
    set(valid FALSE)
  endif()
  set(${output} ${valid} PARENT_SCOPE)
endfunction()

is_uint64_nonzero("18446744073709551615" uint64_max_valid)
is_uint64_nonzero("18446744073709551616" uint64_overflow_valid)
if(NOT uint64_max_valid OR uint64_overflow_valid)
  message(FATAL_ERROR "Nonzero uint64 boundary validation is incorrect")
endif()

# Validate candidate payload fields and the scalar/nested constraints used by every core fixture.
function(validate_event_payload event payload label expect_valid)
  set(def_key "EVENT_DEF_${event}")
  if(NOT DEFINED ${def_key})
    message(FATAL_ERROR "${label}: unknown event type ${event}")
  endif()
  set(def_name "${${def_key}}")
  string(JSON payload_schema GET "${journal_schema}" "$defs" "${def_name}" properties payload)
  string(JSON payload_ref ERROR_VARIABLE payload_ref_error GET "${payload_schema}" "$ref")
  if(payload_ref_error STREQUAL "NOTFOUND")
    string(REPLACE "#/$defs/" "" payload_def_name "${payload_ref}")
    string(JSON payload_schema GET "${journal_schema}" "$defs" "${payload_def_name}")
  endif()
  string(JSON allowed_count ERROR_VARIABLE allowed_error LENGTH "${payload_schema}" properties)
  if(NOT allowed_error STREQUAL "NOTFOUND")
    set(allowed_count 0)
  endif()
  set(allowed "")
  if(allowed_count GREATER 0)
    math(EXPR allowed_last "${allowed_count} - 1")
    foreach(index RANGE 0 ${allowed_last})
      string(JSON member MEMBER "${payload_schema}" properties ${index})
      list(APPEND allowed "${member}")
    endforeach()
  endif()
  string(JSON required_count ERROR_VARIABLE required_error LENGTH "${payload_schema}" required)
  set(valid TRUE)
  if(required_error STREQUAL "NOTFOUND" AND required_count GREATER 0)
    math(EXPR required_last "${required_count} - 1")
    foreach(index RANGE 0 ${required_last})
      string(JSON member GET "${payload_schema}" required ${index})
      string(JSON ignored ERROR_VARIABLE member_error TYPE "${payload}" "${member}")
      if(NOT member_error STREQUAL "NOTFOUND")
        set(valid FALSE)
      endif()
    endforeach()
  endif()
  string(JSON payload_count LENGTH "${payload}")
  if(payload_count GREATER 0)
    math(EXPR payload_last "${payload_count} - 1")
    foreach(index RANGE 0 ${payload_last})
      string(JSON member MEMBER "${payload}" ${index})
      list(FIND allowed "${member}" member_index)
      if(member_index EQUAL -1)
        set(valid FALSE)
      endif()
    endforeach()
  endif()
  if(valid)
    if(event STREQUAL "job_created" OR event MATCHES "^session_retain")
      string(JSON value GET "${payload}" session_id)
      is_uuid_v7("${value}" scalar_valid)
      if(NOT scalar_valid)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "resources_committed")
      string(JSON allocation_id GET "${payload}" allocation_id)
      string(JSON allocation_digest GET "${payload}" allocation_digest)
      string(JSON schema_id GET "${payload}" resolved_allocation schema_id)
      string(JSON schema_version GET "${payload}" resolved_allocation schema_version)
      string(JSON payload_utf8 GET "${payload}" resolved_allocation payload_utf8)
      is_sha256("${allocation_digest}" digest_valid)
      string(SHA256 computed_digest "${payload_utf8}")
      string(LENGTH "${payload_utf8}" payload_byte_length)
      string(JSON ignored ERROR_VARIABLE payload_json_error TYPE "${payload_utf8}")
      if(NOT allocation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR
         NOT schema_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR schema_version LESS 1 OR
         payload_byte_length GREATER 65536 OR NOT payload_json_error STREQUAL "NOTFOUND" OR
         NOT digest_valid OR NOT computed_digest STREQUAL allocation_digest)
        set(valid FALSE)
      endif()
      string(JSON nested_count LENGTH "${payload}" resolved_allocation)
      if(NOT nested_count EQUAL 3)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "worker_launch_intent")
      string(JSON operation_id GET "${payload}" operation_id)
      string(JSON allocation_id GET "${payload}" allocation_id)
      string(JSON allocation_digest GET "${payload}" allocation_digest)
      string(JSON worker_id GET "${payload}" worker_id)
      string(JSON application_id GET "${payload}" application application_id)
      string(JSON application_version GET "${payload}" application version)
      string(JSON bundle_digest GET "${payload}" application bundle_sha256)
      is_uuid_v4("${worker_id}" worker_valid)
      is_sha256("${allocation_digest}" allocation_digest_valid)
      is_sha256("${bundle_digest}" bundle_digest_valid)
      string(JSON application_count LENGTH "${payload}" application)
      if(NOT operation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR
         NOT allocation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR
         NOT application_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR
         application_version STREQUAL "" OR NOT worker_valid OR NOT allocation_digest_valid OR
         NOT bundle_digest_valid OR NOT application_count EQUAL 3)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "worker_launch_observed")
      string(JSON operation_id GET "${payload}" operation_id)
      string(JSON outcome GET "${payload}" outcome)
      if(NOT operation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR
         NOT outcome MATCHES "^(started|failed)$")
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "worker_running")
      string(JSON worker_id GET "${payload}" worker_id)
      is_uuid_v4("${worker_id}" valid)
    elseif(event MATCHES "^worker_(completed|failed)$")
      string(JSON worker_id GET "${payload}" worker_id)
      string(JSON sequence GET "${payload}" event_sequence)
      is_uuid_v4("${worker_id}" worker_valid)
      is_uint64_nonzero("${sequence}" sequence_valid)
      if(NOT worker_valid OR NOT sequence_valid)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "cancel_accepted" OR event STREQUAL "terminate_accepted")
      string(JSON principal GET "${payload}" principal_subject)
      string(LENGTH "${principal}" principal_length)
      if(principal_length LESS 1 OR principal_length GREATER 256)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "timeout_expired")
      string(JSON phase GET "${payload}" phase)
      string(JSON generation GET "${payload}" timer_generation)
      list(FIND timeout_phases "${phase}" phase_index)
      is_uint64_nonzero("${generation}" generation_valid)
      if(phase_index EQUAL -1 OR NOT generation_valid)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "process_exit_confirmed")
      string(JSON mode GET "${payload}" completion_mode)
      string(JSON operation_id GET "${payload}" launch_operation_id)
      if(NOT mode MATCHES "^(cooperative|forced|process_already_exited)$" OR
         NOT operation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$")
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "terminal_outcome_committed")
      string(JSON outcome GET "${payload}" outcome)
      list(FIND terminal_outcomes "${outcome}" outcome_index)
      if(outcome_index EQUAL -1)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "resources_released")
      string(JSON allocation_id GET "${payload}" allocation_id)
      string(JSON allocation_digest GET "${payload}" allocation_digest)
      is_sha256("${allocation_digest}" digest_valid)
      if(NOT allocation_id MATCHES "^[A-Za-z0-9][A-Za-z0-9._:-]*$" OR NOT digest_valid)
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "cleanup_status_recorded")
      string(JSON status GET "${payload}" status)
      if(NOT status MATCHES "^(completed|incomplete)$")
        set(valid FALSE)
      endif()
    elseif(event STREQUAL "late_worker_event")
      string(JSON original GET "${payload}" original_event_type)
      string(JSON worker_id GET "${payload}" worker_id)
      string(JSON sequence GET "${payload}" event_sequence)
      is_uuid_v4("${worker_id}" worker_valid)
      is_uint64_nonzero("${sequence}" sequence_valid)
      if(NOT original MATCHES "^worker_(completed|failed)$" OR NOT worker_valid OR
         NOT sequence_valid)
        set(valid FALSE)
      endif()
    endif()
  endif()
  if(expect_valid AND NOT valid)
    message(FATAL_ERROR "${label}: payload violates its strict event schema constraints")
  elseif(NOT expect_valid AND valid)
    message(FATAL_ERROR "${label}: invalid-payload fixture is unexpectedly valid")
  endif()
endfunction()

# Validate closed predicate/update syntax and build direct pair indexes.
set(payload_fields phase timer_generation outcome operation_id launch_operation_id session_id
                   allocation_id allocation_digest worker_id event_sequence completion_mode status)
set(expected_event_pairs "")
set(actual_event_pairs "")
set(expected_command_pairs "")
set(actual_command_pairs "")
set(expected_edges "")
set(expected_case_keys "")

foreach(position IN LISTS positions)
  foreach(event IN LISTS events)
    list(APPEND expected_event_pairs "${position}__${event}")
  endforeach()
  foreach(command IN LISTS commands)
    list(APPEND expected_command_pairs "${position}__${command}")
  endforeach()
endforeach()

function(validate_when matrix row_index case_index pair_id)
  string(JSON when_operator GET "${contract}" ${matrix} ${row_index} cases ${case_index} when operator)
  if(when_operator STREQUAL "all")
    string(JSON predicate_count LENGTH "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates)
    if(predicate_count LESS 1)
      message(FATAL_ERROR "${pair_id}: all predicate list is empty")
    endif()
    math(EXPR predicate_last "${predicate_count} - 1")
    foreach(predicate_index RANGE 0 ${predicate_last})
      string(JSON source GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
             ${predicate_index} source)
      string(JSON field GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
             ${predicate_index} field)
      string(JSON operator GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
             ${predicate_index} operator)
      if(source STREQUAL "snapshot")
        list(FIND snapshot_fields "${field}" field_index)
      elseif(source STREQUAL "payload")
        list(FIND payload_fields "${field}" field_index)
      else()
        set(field_index -1)
      endif()
      if(field_index EQUAL -1 OR NOT operator MATCHES "^(eq|not_eq|in|eq_field)$")
        message(FATAL_ERROR "${pair_id}: unknown predicate ${source}.${field}/${operator}")
      endif()
    endforeach()
  elseif(NOT when_operator MATCHES "^(always|otherwise)$")
    message(FATAL_ERROR "${pair_id}: unknown when operator ${when_operator}")
  endif()
endfunction()

foreach(matrix IN ITEMS event_matrix command_matrix)
  string(JSON row_count LENGTH "${contract}" ${matrix})
  math(EXPR row_last "${row_count} - 1")
  foreach(row_index RANGE 0 ${row_last})
    string(JSON pair_id GET "${contract}" ${matrix} ${row_index} pair_id)
    string(JSON position GET "${contract}" ${matrix} ${row_index} entity_position)
    if(matrix STREQUAL "event_matrix")
      string(JSON input_kind GET "${contract}" ${matrix} ${row_index} event_kind)
      list(APPEND actual_event_pairs "${pair_id}")
      set("EVENT_ROW_${pair_id}" "${row_index}")
    else()
      string(JSON input_kind GET "${contract}" ${matrix} ${row_index} command_kind)
      list(APPEND actual_command_pairs "${pair_id}")
      set("COMMAND_ROW_${pair_id}" "${row_index}")
    endif()
    if(NOT pair_id STREQUAL "${position}__${input_kind}")
      message(FATAL_ERROR "Invalid pair_id: ${pair_id}")
    endif()

    string(JSON case_count LENGTH "${contract}" ${matrix} ${row_index} cases)
    math(EXPR case_last "${case_count} - 1")
    foreach(case_index RANGE 0 ${case_last})
      string(JSON case_id GET "${contract}" ${matrix} ${row_index} cases ${case_index} case_id)
      string(JSON disposition GET "${contract}" ${matrix} ${row_index} cases ${case_index} disposition)
      list(FIND dispositions "${disposition}" disposition_index)
      if(disposition_index EQUAL -1)
        message(FATAL_ERROR "${pair_id}/${case_id}: unknown disposition ${disposition}")
      endif()
      validate_when(${matrix} ${row_index} ${case_index} "${pair_id}")
      string(JSON when_operator GET "${contract}" ${matrix} ${row_index} cases ${case_index} when operator)
      if(case_count GREATER 1 AND case_index EQUAL case_last AND NOT when_operator STREQUAL "otherwise")
        message(FATAL_ERROR "${pair_id}: ordered cases lack a final otherwise")
      endif()
      if(case_count GREATER 1 AND case_index LESS case_last AND when_operator MATCHES "^(always|otherwise)$")
        message(FATAL_ERROR "${pair_id}: an unconditional case makes later cases unreachable")
      endif()

      if(matrix STREQUAL "event_matrix")
        list(APPEND expected_case_keys "event__${pair_id}__${case_id}")
      else()
        list(APPEND expected_case_keys "command__${pair_id}__${case_id}")
      endif()

      if(disposition STREQUAL "reject")
        string(JSON reason GET "${contract}" ${matrix} ${row_index} cases ${case_index} rejection_reason)
        list(FIND rejections "${reason}" reason_index)
        if(reason_index EQUAL -1)
          message(FATAL_ERROR "${pair_id}/${case_id}: unknown rejection reason ${reason}")
        endif()
      else()
        string(JSON journal_event GET "${contract}" ${matrix} ${row_index} cases ${case_index}
               journal_event_type)
        list(FIND events "${journal_event}" journal_event_index)
        if(journal_event_index EQUAL -1)
          message(FATAL_ERROR "${pair_id}/${case_id}: unknown Journal event ${journal_event}")
        endif()
        string(JSON effect_count ERROR_VARIABLE effect_error LENGTH "${contract}" ${matrix} ${row_index}
               cases ${case_index} post_sync_effects)
        if(effect_error STREQUAL "NOTFOUND" AND effect_count GREATER 0)
          math(EXPR effect_last "${effect_count} - 1")
          foreach(effect_index RANGE 0 ${effect_last})
            string(JSON effect GET "${contract}" ${matrix} ${row_index} cases ${case_index}
                   post_sync_effects ${effect_index})
            list(FIND effects "${effect}" effect_known)
            if(effect_known EQUAL -1)
              message(FATAL_ERROR "${pair_id}/${case_id}: unknown effect ${effect}")
            endif()
          endforeach()
        endif()
      endif()

      string(JSON update_count ERROR_VARIABLE update_error LENGTH "${contract}" ${matrix} ${row_index}
             cases ${case_index} updates)
      if(update_error STREQUAL "NOTFOUND" AND update_count GREATER 0)
        math(EXPR update_last "${update_count} - 1")
        foreach(update_index RANGE 0 ${update_last})
          string(JSON field MEMBER "${contract}" ${matrix} ${row_index} cases ${case_index} updates
                 ${update_index})
          list(FIND snapshot_fields "${field}" field_index)
          if(field_index EQUAL -1 OR field STREQUAL "state" OR field STREQUAL "schema_version")
            message(FATAL_ERROR "${pair_id}/${case_id}: unknown or reserved snapshot update ${field}")
          endif()
        endforeach()
      endif()

      if(disposition STREQUAL "transition")
        string(JSON next_state GET "${contract}" ${matrix} ${row_index} cases ${case_index} next_state)
        list(FIND states "${next_state}" next_state_index)
        if(next_state_index EQUAL -1)
          message(FATAL_ERROR "${pair_id}/${case_id}: unknown next state ${next_state}")
        endif()
        if(matrix STREQUAL "event_matrix")
          list(APPEND expected_edges "${position}|${input_kind}|${next_state}")
        endif()
      endif()
    endforeach()
  endforeach()
endforeach()

# A first accepted process exit ends the bound terminal Worker-event ACK obligation.
string(JSON event_matrix_count LENGTH "${contract}" event_matrix)
math(EXPR event_matrix_last "${event_matrix_count} - 1")
foreach(row_index RANGE 0 ${event_matrix_last})
  string(JSON event_kind GET "${contract}" event_matrix ${row_index} event_kind)
  if(NOT event_kind STREQUAL "process_exit_confirmed")
    continue()
  endif()
  string(JSON case_count LENGTH "${contract}" event_matrix ${row_index} cases)
  math(EXPR case_last "${case_count} - 1")
  foreach(case_index RANGE 0 ${case_last})
    string(JSON case_id GET "${contract}" event_matrix ${row_index} cases ${case_index} case_id)
    string(JSON disposition GET "${contract}" event_matrix ${row_index} cases ${case_index} disposition)
    if(disposition STREQUAL "reject" OR case_id STREQUAL "matching_duplicate")
      continue()
    endif()
    string(JSON ack_type TYPE "${contract}" event_matrix ${row_index} cases ${case_index} updates
           pending_worker_event_ack)
    string(JSON ack_value GET "${contract}" event_matrix ${row_index} cases ${case_index} updates
           pending_worker_event_ack)
    string(JSON worker_type TYPE "${contract}" event_matrix ${row_index} cases ${case_index} updates
           pending_worker_id)
    string(JSON sequence_type TYPE "${contract}" event_matrix ${row_index} cases ${case_index} updates
           pending_worker_event_sequence)
    if(NOT ack_type STREQUAL "BOOLEAN" OR ack_value OR NOT worker_type STREQUAL "NULL" OR
       NOT sequence_type STREQUAL "NULL")
      message(FATAL_ERROR "process_exit_confirmed/${case_id}: ACK binding is not cleared")
    endif()
  endforeach()
endforeach()

foreach(kind IN ITEMS event command)
  set(actual "${actual_${kind}_pairs}")
  set(expected "${expected_${kind}_pairs}")
  assert_unique("${actual}" "${kind} pair IDs")
  list(SORT actual)
  list(SORT expected)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "${kind} matrix does not explicitly cover every pair")
  endif()
endforeach()

# Evaluate the closed predicate AST against a concrete vector.
function(operand_signature source field snapshot payload output)
  if(source STREQUAL "snapshot")
    json_signature("${snapshot}" signature ${field})
  else()
    json_signature("${payload}" signature ${field})
  endif()
  set(${output} "${signature}" PARENT_SCOPE)
endfunction()

function(case_matches matrix row_index case_index snapshot payload output)
  string(JSON when_operator GET "${contract}" ${matrix} ${row_index} cases ${case_index} when operator)
  if(when_operator MATCHES "^(always|otherwise)$")
    set(${output} TRUE PARENT_SCOPE)
    return()
  endif()
  string(JSON predicate_count LENGTH "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates)
  math(EXPR predicate_last "${predicate_count} - 1")
  foreach(predicate_index RANGE 0 ${predicate_last})
    string(JSON source GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
           ${predicate_index} source)
    string(JSON field GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
           ${predicate_index} field)
    string(JSON operator GET "${contract}" ${matrix} ${row_index} cases ${case_index} when predicates
           ${predicate_index} operator)
    operand_signature("${source}" "${field}" "${snapshot}" "${payload}" left)
    set(matched FALSE)
    if(operator MATCHES "^(eq|not_eq)$")
      json_signature("${contract}" right ${matrix} ${row_index} cases ${case_index} when predicates
                     ${predicate_index} value)
      if(left STREQUAL right)
        set(matched TRUE)
      endif()
      if(operator STREQUAL "not_eq")
        if(matched)
          set(matched FALSE)
        else()
          set(matched TRUE)
        endif()
      endif()
    elseif(operator STREQUAL "in")
      string(JSON value_count LENGTH "${contract}" ${matrix} ${row_index} cases ${case_index} when
             predicates ${predicate_index} values)
      math(EXPR value_last "${value_count} - 1")
      foreach(value_index RANGE 0 ${value_last})
        json_signature("${contract}" right ${matrix} ${row_index} cases ${case_index} when predicates
                       ${predicate_index} values ${value_index})
        if(left STREQUAL right)
          set(matched TRUE)
        endif()
      endforeach()
    elseif(operator STREQUAL "eq_field")
      string(JSON right_source GET "${contract}" ${matrix} ${row_index} cases ${case_index} when
             predicates ${predicate_index} right_source)
      string(JSON right_field GET "${contract}" ${matrix} ${row_index} cases ${case_index} when
             predicates ${predicate_index} right_field)
      operand_signature("${right_source}" "${right_field}" "${snapshot}" "${payload}" right)
      if(left STREQUAL right)
        set(matched TRUE)
      endif()
    endif()
    if(NOT matched)
      set(${output} FALSE PARENT_SCOPE)
      return()
    endif()
  endforeach()
  set(${output} TRUE PARENT_SCOPE)
endfunction()

function(select_case matrix row_index snapshot payload output_index output_id)
  string(JSON case_count LENGTH "${contract}" ${matrix} ${row_index} cases)
  math(EXPR case_last "${case_count} - 1")
  foreach(case_index RANGE 0 ${case_last})
    case_matches(${matrix} ${row_index} ${case_index} "${snapshot}" "${payload}" matches)
    if(matches)
      string(JSON case_id GET "${contract}" ${matrix} ${row_index} cases ${case_index} case_id)
      set(${output_index} "${case_index}" PARENT_SCOPE)
      set(${output_id} "${case_id}" PARENT_SCOPE)
      return()
    endif()
  endforeach()
  message(FATAL_ERROR "No ordered case matched")
endfunction()

function(resolve_update matrix row_index case_index field initial_snapshot input payload output)
  string(JSON value_type TYPE "${contract}" ${matrix} ${row_index} cases ${case_index} updates ${field})
  if(value_type STREQUAL "OBJECT")
    string(JSON from GET "${contract}" ${matrix} ${row_index} cases ${case_index} updates ${field} from)
    string(REPLACE "." ";" parts "${from}")
    list(GET parts 0 source)
    list(GET parts 1 source_field)
    if(source STREQUAL "payload")
      json_signature("${payload}" signature ${source_field})
    else()
      json_signature("${input}" signature ${source_field})
    endif()
  else()
    json_signature("${contract}" signature ${matrix} ${row_index} cases ${case_index} updates ${field})
  endif()
  set(${output} "${signature}" PARENT_SCOPE)
endfunction()

function(validate_expected matrix row_index case_index initial_snapshot input payload expected expected_sequence label)
  string(JSON disposition GET "${contract}" ${matrix} ${row_index} cases ${case_index} disposition)
  string(JSON expected_disposition GET "${expected}" disposition)
  if(NOT disposition STREQUAL expected_disposition)
    message(FATAL_ERROR "${label}: disposition differs from matrix")
  endif()

  string(JSON expected_effect_count LENGTH "${expected}" post_sync_effects)
  string(JSON contract_effect_count ERROR_VARIABLE effect_error LENGTH "${contract}" ${matrix} ${row_index}
         cases ${case_index} post_sync_effects)
  if(NOT effect_error STREQUAL "NOTFOUND")
    set(contract_effect_count 0)
  endif()
  if(NOT expected_effect_count EQUAL contract_effect_count)
    message(FATAL_ERROR "${label}: post-sync effect count differs from matrix")
  endif()
  if(expected_effect_count GREATER 0)
    math(EXPR effect_last "${expected_effect_count} - 1")
    foreach(effect_index RANGE 0 ${effect_last})
      string(JSON expected_effect GET "${expected}" post_sync_effects ${effect_index})
      string(JSON contract_effect GET "${contract}" ${matrix} ${row_index} cases ${case_index}
             post_sync_effects ${effect_index})
      if(NOT expected_effect STREQUAL contract_effect)
        message(FATAL_ERROR "${label}: post-sync effect order differs from matrix")
      endif()
    endforeach()
  endif()

  if(disposition STREQUAL "reject")
    string(JSON reason GET "${contract}" ${matrix} ${row_index} cases ${case_index} rejection_reason)
    string(JSON expected_reason GET "${expected}" rejection_reason)
    if(NOT reason STREQUAL expected_reason)
      message(FATAL_ERROR "${label}: rejection reason differs from matrix")
    endif()
    string(JSON journal_type TYPE "${expected}" journal_event)
    if(NOT journal_type STREQUAL "NULL")
      message(FATAL_ERROR "${label}: rejected input has a Journal event")
    endif()
  else()
    string(JSON event_type GET "${contract}" ${matrix} ${row_index} cases ${case_index} journal_event_type)
    string(JSON expected_event_type GET "${expected}" journal_event event_type)
    string(JSON expected_event_sequence GET "${expected}" journal_event sequence)
    if(NOT event_type STREQUAL expected_event_type OR NOT expected_event_sequence EQUAL expected_sequence)
      message(FATAL_ERROR "${label}: Journal event type or sequence differs")
    endif()
    string(JSON expected_payload GET "${expected}" journal_event payload)
    validate_event_payload("${event_type}" "${expected_payload}" "${label}" TRUE)
    if(matrix STREQUAL "event_matrix")
      string(JSON normalize_type ERROR_VARIABLE normalize_error GET "${contract}" ${matrix} ${row_index}
             cases ${case_index} normalize_to)
      if(normalize_error STREQUAL "NOTFOUND")
        string(JSON original_event GET "${input}" event_type)
        string(JSON normalized_original GET "${expected}" journal_event payload original_event_type)
        if(NOT original_event STREQUAL normalized_original)
          message(FATAL_ERROR "${label}: late event normalization lost the original event type")
        endif()
      else()
        json_signature("${input}" input_payload_signature payload)
        json_signature("${expected}" journal_payload_signature journal_event payload)
        if(NOT input_payload_signature STREQUAL journal_payload_signature)
          message(FATAL_ERROR "${label}: accepted candidate payload was not copied to the Journal")
        endif()
      endif()
    else()
      string(JSON principal GET "${input}" principal_subject)
      string(JSON journal_principal GET "${expected}" journal_event payload principal_subject)
      if(NOT principal STREQUAL journal_principal)
        message(FATAL_ERROR "${label}: accepted command principal was not copied")
      endif()
    endif()
    string(JSON expected_reason_type TYPE "${expected}" rejection_reason)
    if(NOT expected_reason_type STREQUAL "NULL")
      message(FATAL_ERROR "${label}: accepted input has a rejection reason")
    endif()
  endif()

  # Verify the full expected next snapshot against next_state, updates, and unchanged fields.
  string(JSON expected_snapshot_type TYPE "${expected}" next_snapshot)
  string(JSON initial_type TYPE "${initial_snapshot}")
  if(disposition STREQUAL "reject" AND initial_type STREQUAL "NULL")
    if(NOT expected_snapshot_type STREQUAL "NULL")
      message(FATAL_ERROR "${label}: missing Job rejection created a snapshot")
    endif()
    return()
  endif()
  if(NOT expected_snapshot_type STREQUAL "OBJECT")
    message(FATAL_ERROR "${label}: expected next snapshot is not an object")
  endif()
  string(JSON expected_snapshot GET "${expected}" next_snapshot)
  foreach(field IN LISTS snapshot_fields)
    if(field STREQUAL "schema_version" AND initial_type STREQUAL "NULL")
      set(expected_signature "NUMBER:1")
    elseif(field STREQUAL "state")
      string(JSON next_state ERROR_VARIABLE next_error GET "${contract}" ${matrix} ${row_index} cases
             ${case_index} next_state)
      if(next_error STREQUAL "NOTFOUND")
        set(expected_signature "STRING:${next_state}")
      elseif(initial_type STREQUAL "NULL")
        set(expected_signature "MISSING")
      else()
        json_signature("${initial_snapshot}" expected_signature state)
      endif()
    else()
      string(JSON update_type ERROR_VARIABLE update_error TYPE "${contract}" ${matrix} ${row_index} cases
             ${case_index} updates ${field})
      if(update_error STREQUAL "NOTFOUND")
        resolve_update(${matrix} ${row_index} ${case_index} "${field}" "${initial_snapshot}"
                       "${input}" "${payload}" expected_signature)
      elseif(initial_type STREQUAL "NULL")
        set(expected_signature "MISSING")
      else()
        json_signature("${initial_snapshot}" expected_signature ${field})
      endif()
    endif()
    json_signature("${expected_snapshot}" actual_signature ${field})
    if(NOT expected_signature STREQUAL actual_signature)
      message(FATAL_ERROR "${label}: next snapshot field ${field} differs: ${expected_signature} != ${actual_signature}")
    endif()
  endforeach()
endfunction()

function(validate_snapshot_invariants snapshot label)
  string(JSON job_id GET "${snapshot}" job_id)
  string(JSON session_id GET "${snapshot}" session_id)
  string(JSON state GET "${snapshot}" state)
  string(JSON resource_status GET "${snapshot}" resource_status)
  string(JSON worker_launch_status GET "${snapshot}" worker_launch_status)
  string(JSON process_presence GET "${snapshot}" process_presence)
  string(JSON process_exit_confirmed GET "${snapshot}" process_exit_confirmed)
  string(JSON finalization_status GET "${snapshot}" finalization_status)
  string(JSON pending_ack GET "${snapshot}" pending_worker_event_ack)
  string(JSON completion_mode_type TYPE "${snapshot}" completion_mode)
  if(NOT job_id STREQUAL session_id)
    message(FATAL_ERROR "${label}: v0.1 Job and Session identity differ")
  endif()
  json_signature("${snapshot}" allocation_id allocation_id)
  json_signature("${snapshot}" allocation_digest allocation_digest)
  json_signature("${snapshot}" launch_operation_id launch_operation_id)
  json_signature("${snapshot}" worker_id worker_id)
  json_signature("${snapshot}" pending_worker_id pending_worker_id)
  json_signature("${snapshot}" pending_worker_sequence pending_worker_event_sequence)
  if(resource_status STREQUAL "none")
    if(NOT allocation_id STREQUAL "NULL" OR NOT allocation_digest STREQUAL "NULL")
      message(FATAL_ERROR "${label}: uncommitted resources have allocation bindings")
    endif()
  elseif(allocation_id STREQUAL "NULL" OR allocation_digest STREQUAL "NULL")
    message(FATAL_ERROR "${label}: committed resources lack allocation bindings")
  endif()
  if(resource_status STREQUAL "released" AND NOT process_exit_confirmed)
    message(FATAL_ERROR "${label}: resources were released before confirmed process exit")
  endif()
  if(process_exit_confirmed AND NOT process_presence STREQUAL "absent")
    message(FATAL_ERROR "${label}: confirmed process exit retains process presence")
  endif()
  if(completion_mode_type STREQUAL "STRING")
    string(JSON completion_mode GET "${snapshot}" completion_mode)
    if(completion_mode STREQUAL "process_already_exited" AND NOT process_exit_confirmed)
      message(FATAL_ERROR "${label}: process_already_exited lacks exit confirmation")
    endif()
  endif()
  if(worker_launch_status STREQUAL "not_started")
    if(NOT launch_operation_id STREQUAL "NULL" OR NOT worker_id STREQUAL "NULL")
      message(FATAL_ERROR "${label}: not-started Worker has launch bindings")
    endif()
  elseif(launch_operation_id STREQUAL "NULL" OR worker_id STREQUAL "NULL")
    message(FATAL_ERROR "${label}: launched Worker lacks operation or Worker identity")
  endif()
  if(pending_ack)
    if(pending_worker_id STREQUAL "NULL" OR pending_worker_sequence STREQUAL "NULL")
      message(FATAL_ERROR "${label}: pending ACK lacks Worker identity or sequence")
    endif()
  elseif(NOT pending_worker_id STREQUAL "NULL" OR NOT pending_worker_sequence STREQUAL "NULL")
    message(FATAL_ERROR "${label}: non-pending ACK retains Worker identity or sequence")
  endif()
  if(state MATCHES "^(admitted|preparing|running|stopping)$" AND
     NOT finalization_status STREQUAL "not_started")
    message(FATAL_ERROR "${label}: pre-finalization state has finalization status ${finalization_status}")
  elseif(state STREQUAL "finalizing" AND NOT finalization_status MATCHES "^(pending|completed|failed)$")
    message(FATAL_ERROR "${label}: finalizing has invalid finalization status")
  elseif(state MATCHES "^(succeeded|failed|cancelled|terminated|timed_out)$" AND
         NOT finalization_status MATCHES "^(completed|failed)$")
    message(FATAL_ERROR "${label}: terminal state lacks a finalization result")
  endif()
  if(state STREQUAL "admitted" AND
     (NOT resource_status STREQUAL "none" OR NOT worker_launch_status STREQUAL "not_started" OR
      NOT process_presence STREQUAL "absent" OR process_exit_confirmed))
    message(FATAL_ERROR "${label}: admitted snapshot violates its cross-field invariant")
  endif()
endfunction()

# Every matrix case has one concrete, invariant-valid vector with deep expected values.
set(actual_case_keys "")
string(JSON vector_count LENGTH "${vectors}" case_vectors)
math(EXPR vector_last "${vector_count} - 1")
foreach(vector_index RANGE 0 ${vector_last})
  string(JSON matrix_short GET "${vectors}" case_vectors ${vector_index} matrix)
  string(JSON pair_id GET "${vectors}" case_vectors ${vector_index} pair_id)
  string(JSON declared_case_id GET "${vectors}" case_vectors ${vector_index} case_id)
  string(JSON vector_id GET "${vectors}" case_vectors ${vector_index} vector_id)
  set(matrix "${matrix_short}_matrix")
  set(row_key "${matrix_short}")
  string(TOUPPER "${matrix_short}" row_key)
  set(index_variable "${row_key}_ROW_${pair_id}")
  if(NOT DEFINED ${index_variable})
    message(FATAL_ERROR "${vector_id}: unknown matrix pair")
  endif()
  set(row_index "${${index_variable}}")
  string(JSON initial_snapshot_type TYPE "${vectors}" case_vectors ${vector_index} initial_snapshot)
  if(initial_snapshot_type STREQUAL "NULL")
    set(initial_snapshot "null")
  else()
    string(JSON initial_snapshot GET "${vectors}" case_vectors ${vector_index} initial_snapshot)
  endif()
  string(JSON input GET "${vectors}" case_vectors ${vector_index} input)
  string(JSON input_type TYPE "${input}")
  if(matrix_short STREQUAL "event")
    string(JSON payload GET "${input}" payload)
    string(JSON event GET "${input}" event_type)
    validate_event_payload("${event}" "${payload}" "${vector_id}" TRUE)
  else()
    set(payload "{}")
  endif()
  select_case(${matrix} ${row_index} "${initial_snapshot}" "${payload}" selected_index selected_id)
  if(NOT selected_id STREQUAL declared_case_id OR
     NOT vector_id STREQUAL "${matrix_short}__${pair_id}__${declared_case_id}")
    message(FATAL_ERROR "${vector_id}: vector is unreachable or misidentified; selected ${selected_id}")
  endif()
  list(APPEND actual_case_keys "${matrix_short}__${pair_id}__${declared_case_id}")
  string(JSON expected GET "${vectors}" case_vectors ${vector_index} expected)
  if(NOT initial_snapshot_type STREQUAL "NULL")
    validate_snapshot_invariants("${initial_snapshot}" "${vector_id}/initial")
  endif()
  validate_expected(${matrix} ${row_index} ${selected_index} "${initial_snapshot}" "${input}"
                    "${payload}" "${expected}" 1 "${vector_id}")
  string(JSON next_snapshot_type TYPE "${expected}" next_snapshot)
  if(next_snapshot_type STREQUAL "OBJECT")
    string(JSON next_snapshot GET "${expected}" next_snapshot)
    validate_snapshot_invariants("${next_snapshot}" "${vector_id}/next")
  endif()
endforeach()
assert_unique("${actual_case_keys}" "case vector IDs")
list(SORT actual_case_keys)
list(SORT expected_case_keys)
if(NOT actual_case_keys STREQUAL expected_case_keys)
  message(FATAL_ERROR "Concrete vectors do not cover every ordered matrix case")
endif()

# Every event kind has a concrete invalid payload that fails the closed field inventory.
set(invalid_events "")
string(JSON invalid_count LENGTH "${vectors}" invalid_payload_vectors)
math(EXPR invalid_last "${invalid_count} - 1")
foreach(index RANGE 0 ${invalid_last})
  string(JSON vector_id GET "${vectors}" invalid_payload_vectors ${index} vector_id)
  string(JSON event GET "${vectors}" invalid_payload_vectors ${index} input event_type)
  string(JSON payload GET "${vectors}" invalid_payload_vectors ${index} input payload)
  string(JSON reason GET "${vectors}" invalid_payload_vectors ${index} expected rejection_reason)
  if(NOT reason STREQUAL "invalid_event_payload")
    message(FATAL_ERROR "${vector_id}: invalid payload has the wrong rejection reason")
  endif()
  validate_event_payload("${event}" "${payload}" "${vector_id}" FALSE)
  list(APPEND invalid_events "${event}")
endforeach()
list(REMOVE_DUPLICATES invalid_events)
list(SORT invalid_events)
set(sorted_events ${events})
list(SORT sorted_events)
if(NOT invalid_events STREQUAL sorted_events)
  message(FATAL_ERROR "Invalid-payload vectors do not cover every event kind")
endif()

# Required race/finalization/cleanup vectors are concrete, sequential, and chain snapshots and sequence.
set(required_sequences
    race__cancel_before_timeout
    race__timeout_before_cancel
    race__cancel_before_worker_completed
    race__worker_completed_before_cancel
    race__terminate_before_worker_completed
    race__worker_completed_before_terminate
    race__worker_failed_before_process_exit
    race__process_exit_before_worker_failed
    finalization__worker_completed_then_failure
    finalization__execution_timeout_before_success_commit
    cleanup__success_then_exit_timeout
    cleanup__matching_duplicate_exit
    cleanup__conflicting_duplicate_exit
    cleanup__status_regression)
set(actual_sequences "")
string(JSON sequence_count LENGTH "${vectors}" sequence_vectors)
math(EXPR sequence_last "${sequence_count} - 1")
foreach(vector_index RANGE 0 ${sequence_last})
  string(JSON vector_id GET "${vectors}" sequence_vectors ${vector_index} vector_id)
  list(APPEND actual_sequences "${vector_id}")
  string(JSON current_snapshot GET "${vectors}" sequence_vectors ${vector_index} initial_snapshot)
  validate_snapshot_invariants("${current_snapshot}" "${vector_id}/initial")
  set(expected_sequence 1)
  string(JSON step_count LENGTH "${vectors}" sequence_vectors ${vector_index} steps)
  if(step_count LESS 2)
    message(FATAL_ERROR "${vector_id}: sequence vector has fewer than two steps")
  endif()
  math(EXPR step_last "${step_count} - 1")
  foreach(step_index RANGE 0 ${step_last})
    string(JSON input GET "${vectors}" sequence_vectors ${vector_index} steps ${step_index} input)
    string(JSON expected GET "${vectors}" sequence_vectors ${vector_index} steps ${step_index} expected)
    string(JSON command_type ERROR_VARIABLE command_error GET "${input}" command_type)
    if(command_error STREQUAL "NOTFOUND")
      string(JSON command_case_id GET "${vectors}" sequence_vectors ${vector_index} steps ${step_index}
             command_case_id)
      string(JSON state GET "${current_snapshot}" state)
      set(row_key "COMMAND_ROW_${state}__${command_type}")
      set(row_index "${${row_key}}")
      set(payload "{}")
      select_case(command_matrix ${row_index} "${current_snapshot}" "${payload}" command_case_index
                  selected_command_case)
      if(NOT selected_command_case STREQUAL command_case_id)
        message(FATAL_ERROR "${vector_id}/${step_index}: wrong command case")
      endif()
      string(JSON command_disposition GET "${contract}" command_matrix ${row_index} cases
             ${command_case_index} disposition)
      if(command_disposition STREQUAL "reject")
        string(JSON event_case_type TYPE "${vectors}" sequence_vectors ${vector_index} steps ${step_index}
               event_case_id)
        if(NOT event_case_type STREQUAL "NULL")
          message(FATAL_ERROR "${vector_id}/${step_index}: rejected command has an event case")
        endif()
        validate_expected(command_matrix ${row_index} ${command_case_index} "${current_snapshot}"
                          "${input}" "${payload}" "${expected}" ${expected_sequence}
                          "${vector_id}/${step_index}")
      else()
        string(JSON accepted_event GET "${contract}" command_matrix ${row_index} cases
               ${command_case_index} journal_event_type)
        string(JSON principal GET "${input}" principal_subject)
        set(payload "{}")
        string(JSON payload SET "${payload}" principal_subject "\"${principal}\"")
        set(event_row_key "EVENT_ROW_${state}__${accepted_event}")
        set(event_row_index "${${event_row_key}}")
        select_case(event_matrix ${event_row_index} "${current_snapshot}" "${payload}" event_case_index
                    selected_event_case)
        string(JSON declared_event_case GET "${vectors}" sequence_vectors ${vector_index} steps
               ${step_index} event_case_id)
        if(NOT selected_event_case STREQUAL declared_event_case)
          message(FATAL_ERROR "${vector_id}/${step_index}: wrong accepted-event case")
        endif()
        set(synthetic_input "{}")
        string(JSON synthetic_input SET "${synthetic_input}" schema_version 1)
        string(JSON synthetic_input SET "${synthetic_input}" job_id "\"00000000-0000-7000-8000-000000000000\"")
        string(JSON synthetic_input SET "${synthetic_input}" event_type "\"${accepted_event}\"")
        string(JSON synthetic_input SET "${synthetic_input}" payload "${payload}")
        validate_expected(event_matrix ${event_row_index} ${event_case_index} "${current_snapshot}"
                          "${synthetic_input}" "${payload}" "${expected}" ${expected_sequence}
                          "${vector_id}/${step_index}")
      endif()
    else()
      string(JSON event GET "${input}" event_type)
      string(JSON payload GET "${input}" payload)
      validate_event_payload("${event}" "${payload}" "${vector_id}/${step_index}" TRUE)
      string(JSON state GET "${current_snapshot}" state)
      set(row_key "EVENT_ROW_${state}__${event}")
      set(row_index "${${row_key}}")
      select_case(event_matrix ${row_index} "${current_snapshot}" "${payload}" event_case_index
                  selected_event_case)
      string(JSON declared_event_case GET "${vectors}" sequence_vectors ${vector_index} steps ${step_index}
             event_case_id)
      if(NOT selected_event_case STREQUAL declared_event_case)
        message(FATAL_ERROR "${vector_id}/${step_index}: wrong event case")
      endif()
      validate_expected(event_matrix ${row_index} ${event_case_index} "${current_snapshot}" "${input}"
                        "${payload}" "${expected}" ${expected_sequence} "${vector_id}/${step_index}")
    endif()
    string(JSON journal_type TYPE "${expected}" journal_event)
    if(NOT journal_type STREQUAL "NULL")
      math(EXPR expected_sequence "${expected_sequence} + 1")
    endif()
    string(JSON current_snapshot GET "${expected}" next_snapshot)
    validate_snapshot_invariants("${current_snapshot}" "${vector_id}/${step_index}/next")
  endforeach()
  string(JSON expected_final GET "${vectors}" sequence_vectors ${vector_index} expected_final_snapshot)
  foreach(field IN LISTS snapshot_fields)
    json_signature("${current_snapshot}" chained_signature ${field})
    json_signature("${expected_final}" declared_signature ${field})
    if(NOT chained_signature STREQUAL declared_signature)
      message(FATAL_ERROR
        "${vector_id}: final snapshot field ${field} differs: ${declared_signature} != ${chained_signature}")
    endif()
  endforeach()
endforeach()
assert_unique("${actual_sequences}" "sequence vector IDs")
list(SORT actual_sequences)
list(SORT required_sequences)
if(NOT actual_sequences STREQUAL required_sequences)
  message(FATAL_ERROR "Required race/finalization/cleanup sequence vectors differ")
endif()

# Timer generation ingress is validated before a timeout candidate or Journal event can exist.
set(required_timer_vectors
    timer__generation_exhausted
    timer__disarmed_notification
    timer__current_notification
    timer__stale_notification)
set(actual_timer_vectors "")
string(JSON timer_vector_count LENGTH "${vectors}" timer_ingress_vectors)
math(EXPR timer_vector_last "${timer_vector_count} - 1")
foreach(index RANGE 0 ${timer_vector_last})
  string(JSON vector_id GET "${vectors}" timer_ingress_vectors ${index} vector_id)
  list(APPEND actual_timer_vectors "${vector_id}")
  string(JSON active_type TYPE "${vectors}" timer_ingress_vectors ${index} active_generation)
  string(JSON notification_type TYPE "${vectors}" timer_ingress_vectors ${index} notification_generation)
  string(JSON arm_requested GET "${vectors}" timer_ingress_vectors ${index} arm_requested)
  if(active_type STREQUAL "NUMBER")
    string(JSON active_generation GET "${vectors}" timer_ingress_vectors ${index} active_generation)
    is_uint64_nonzero("${active_generation}" active_generation_valid)
    if(NOT active_generation_valid)
      message(FATAL_ERROR "${vector_id}: active timer generation is outside uint64")
    endif()
  endif()
  if(notification_type STREQUAL "NUMBER")
    string(JSON notification_generation GET "${vectors}" timer_ingress_vectors ${index}
           notification_generation)
    is_uint64_nonzero("${notification_generation}" notification_generation_valid)
    if(NOT notification_generation_valid)
      message(FATAL_ERROR "${vector_id}: notification timer generation is outside uint64")
    endif()
  endif()
  set(case_id "")
  set(disposition "")
  set(contract_effects "")
  string(JSON timer_case_count LENGTH "${contract}" timer_ingress_contract cases)
  math(EXPR timer_case_last "${timer_case_count} - 1")
  foreach(case_index RANGE 0 ${timer_case_last})
    if(NOT case_id STREQUAL "")
      break()
    endif()
    string(JSON condition GET "${contract}" timer_ingress_contract cases ${case_index} when)
    set(matches FALSE)
    if(condition STREQUAL "arm_requested_at_uint64_max")
      if(arm_requested AND active_type STREQUAL "NUMBER" AND
         active_generation STREQUAL "18446744073709551615")
        set(matches TRUE)
      endif()
    elseif(condition STREQUAL "active_generation_is_null")
      if(active_type STREQUAL "NULL")
        set(matches TRUE)
      endif()
    elseif(condition STREQUAL "notification_generation_equals_active")
      if(notification_type STREQUAL "NUMBER" AND active_type STREQUAL "NUMBER" AND
         notification_generation STREQUAL active_generation)
        set(matches TRUE)
      endif()
    elseif(condition STREQUAL "otherwise")
      set(matches TRUE)
    else()
      message(FATAL_ERROR "Unknown timer ingress predicate: ${condition}")
    endif()
    if(matches)
      string(JSON case_id GET "${contract}" timer_ingress_contract cases ${case_index} case_id)
      string(JSON disposition GET "${contract}" timer_ingress_contract cases ${case_index} disposition)
      string(JSON effects_length ERROR_VARIABLE effects_error LENGTH "${contract}"
             timer_ingress_contract cases ${case_index} post_sync_effects)
      if(effects_error STREQUAL "NOTFOUND")
        read_string_array("${contract}" contract_effects timer_ingress_contract cases ${case_index}
                          post_sync_effects)
      endif()
    endif()
  endforeach()
  if(case_id STREQUAL "")
    message(FATAL_ERROR "${vector_id}: timer ingress contract selected no case")
  endif()
  string(JSON expected_case GET "${vectors}" timer_ingress_vectors ${index} expected case_id)
  string(JSON expected_disposition GET "${vectors}" timer_ingress_vectors ${index} expected disposition)
  read_string_array("${vectors}" expected_timer_effects timer_ingress_vectors ${index} expected
                    post_sync_effects)
  if(NOT case_id STREQUAL expected_case OR NOT disposition STREQUAL expected_disposition OR
     NOT contract_effects STREQUAL expected_timer_effects)
    message(FATAL_ERROR "${vector_id}: timer ingress result differs from the machine contract")
  endif()
  string(JSON candidate_type TYPE "${vectors}" timer_ingress_vectors ${index} expected candidate_event)
  if(disposition STREQUAL "emit_candidate_event")
    if(NOT candidate_type STREQUAL "OBJECT")
      message(FATAL_ERROR "${vector_id}: current timer notification did not emit a candidate")
    endif()
    string(JSON candidate GET "${vectors}" timer_ingress_vectors ${index} expected candidate_event)
    string(JSON event GET "${candidate}" event_type)
    string(JSON payload GET "${candidate}" payload)
    string(JSON candidate_generation GET "${payload}" timer_generation)
    if(NOT event STREQUAL "timeout_expired" OR NOT candidate_generation STREQUAL notification_generation)
      message(FATAL_ERROR "${vector_id}: emitted timeout candidate has the wrong generation")
    endif()
    validate_event_payload("${event}" "${payload}" "${vector_id}" TRUE)
  elseif(NOT candidate_type STREQUAL "NULL")
    message(FATAL_ERROR "${vector_id}: stale, disarmed, or exhausted timer emitted a candidate")
  endif()
endforeach()
assert_unique("${actual_timer_vectors}" "timer ingress vector IDs")
list(SORT actual_timer_vectors)
list(SORT required_timer_vectors)
if(NOT actual_timer_vectors STREQUAL required_timer_vectors)
  message(FATAL_ERROR "Required timer ingress vectors differ")
endif()

# Parse actual DOT edges rather than trusting comments.
string(REGEX MATCHALL
       "[a-z][a-z0-9_]* -> [a-z][a-z0-9_]* [[]label=\"[a-z][a-z0-9_]*\"[]]"
       diagram_edge_lines "${diagram}")
set(diagram_edges "")
foreach(line IN LISTS diagram_edge_lines)
  string(REGEX REPLACE
         "^([a-z][a-z0-9_]*) -> ([a-z][a-z0-9_]*) [[]label=\"([a-z][a-z0-9_]*)\"[]]$"
         "\\1|\\3|\\2" edge "${line}")
  list(APPEND diagram_edges "${edge}")
endforeach()
list(REMOVE_DUPLICATES expected_edges)
assert_unique("${diagram_edges}" "DOT edges")
list(SORT expected_edges)
list(SORT diagram_edges)
if(NOT diagram_edges STREQUAL expected_edges)
  message(FATAL_ERROR "job-state-diagram.dot differs from the transition matrix")
endif()

string(JSON event_row_count LENGTH "${contract}" event_matrix)
string(JSON command_row_count LENGTH "${contract}" command_matrix)
message(STATUS
  "Core Job contract valid: ${event_row_count} event pairs, ${command_row_count} command pairs, "
  "${vector_count} reachable case vectors, ${sequence_count} sequence vectors, "
  "${timer_vector_count} timer ingress vectors")
